version: "2.1"

services:
  event-database:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: event-database
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env

    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
      - event-network


  event-management-service:
    image: event-management-service
    build: .
    depends_on:
      - event-database
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@event-database/${MYSQL_DATABASE}
    env_file: ./.env
    volumes:
      - .:/app
    networks:
      - default
      - event-network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - event-database
    image: phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      - PMA_HOST=event-database
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - default
      - event-network
      - mysql-phpmyadmin

networks:
  event-network:
  mysql-phpmyadmin:

volumes:
  mysql_data:
