"""is deleted

Revision ID: 25b244a990f2
Revises: 51b6cf8bf781
Create Date: 2024-07-19 23:46:33.742501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25b244a990f2'
down_revision = '51b6cf8bf781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('events', 'deleted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.drop_column('events', 'is_deleted')
    # ### end Alembic commands ###
