"""registration model

Revision ID: 50a52bc18428
Revises: 25b244a990f2
Create Date: 2024-07-20 02:50:33.932055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a52bc18428'
down_revision = '25b244a990f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
